# Generated by Django 4.0.6 on 2024-06-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0005_genero_portada_peliculas_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='face',
            field=models.FileField(blank=True, null=True, upload_to='directores'),
        ),
    ]
